name: Generate Podcast feeds
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          node-version: '20'
      - name: Run Feed Generator
        uses: DevDevesh-Tech/podcast-generator@main
